CREATE TABLE SmartPhoneCompany(
CompanyID INT NOT NULL IDENTITY(1,1),
CompanyName CHAR(40) NOT NULL,
CONSTRAINT COMPANY_PK PRIMARY KEY(CompanyID)
);

CREATE TABLE SmartPhoneProducts(
ProductID INT NOT NULL,
ProductName CHAR(40) NOT NULL DEFAULT 'TOUCH TO DIE II',
CompanyNumb INT NOT NULL,
CONSTRAINT PRODUCT_PK PRIMARY KEY(ProductID,CompanyNumb),
CONSTRAINT COMPANY_PRODUCT_FK FOREIGN KEY(CompanyNumb)
            REFERENCES SmartPhoneCompany(CompanyID)
			ON UPDATE CASCADE
			ON DELETE CASCADE
);
